USE AdventureWorks2019
GO

CREATE TABLE SRC_STM_LKP
(SRC_STM_ID INT PRIMARY KEY,
SRC_STM_CODE VARCHAR(6),
CRT_USR_NM VARCHAR(MAX) NOT NULL DEFAULT SUSER_NAME(),
CRT_DTM DATETIME2(7) NOT NULL DEFAULT SYSDATETIME()
);

INSERT INTO SRC_STM_LKP (SRC_STM_ID, SRC_STM_CODE)
VALUES (1, 'STNDRT'),
   	 (2, 'BRKBO1'),
   	 (3, 'INTNTL'),
   	 (4, 'BNKBLN');


--============================================================

CREATE SEQUENCE AcIdSeq AS INT START WITH 1 INCREMENT BY 1;

CREATE TABLE AC_LKP
(AC_ID INT PRIMARY KEY DEFAULT NEXT VALUE FOR AcIdSeq,
AC_NUM VARCHAR(MAX),
ACTV_F VARCHAR(1) NOT NULL DEFAULT 'Y',
CRT_USR_NM VARCHAR(MAX) NOT NULL DEFAULT SUSER_NAME(),
CRT_DTM DATETIME2(7) NOT NULL DEFAULT SYSDATETIME()
);

INSERT INTO AC_LKP (AC_NUM)
SELECT DISTINCT SUBSTRING(CAST(rowguid AS VARCHAR(MAX)), 1, 8)
FROM HumanResources.Employee;

INSERT INTO AC_LKP (AC_NUM, ACTV_F)
SELECT TOP 35 AC_NUM, 'N'
FROM AC_LKP;


--============================================================
CREATE SEQUENCE PdIdSeq AS INT START WITH 1 INCREMENT BY 1;


CREATE TABLE PD_LKP
(PD_ID INT PRIMARY KEY DEFAULT NEXT VALUE FOR PdIdSeq,
PD_NUM VARCHAR(MAX),
EFF_DT DATE NOT NULL,
END_DATE DATE NOT NULL DEFAULT CAST('31-DEC-2099' AS DATE),
--In case on insert you get an error (your PC might be in another language) take the code from below instead of code from above
--END_DATE  DATE NOT NULL DEFAULT CAST('2099-12-31' AS DATE),
CRT_USR_NM VARCHAR(MAX) NOT NULL DEFAULT SUSER_NAME(),
CRT_DTM DATETIME2(7) NOT NULL DEFAULT SYSDATETIME()
);


INSERT INTO PD_LKP (PD_NUM, EFF_DT, END_DATE)
SELECT DISTINCT ProductNumber, DATEADD(DAY, -15 , CAST(SYSDATETIME() AS DATE)), DATEADD(DAY, -5 , CAST(SYSDATETIME() AS DATE))
FROM Production.Product
WHERE ProductNumber < 'BL';

INSERT INTO PD_LKP (PD_NUM, EFF_DT, END_DATE)
SELECT DISTINCT ProductNumber, DATEADD(DAY, -4 , CAST(SYSDATETIME() AS DATE)), DATEADD(DAY, -1 , CAST(SYSDATETIME() AS DATE))
FROM Production.Product
WHERE ProductNumber < 'BL';

INSERT INTO PD_LKP (PD_NUM, EFF_DT)
SELECT DISTINCT ProductNumber, CAST(SYSDATETIME() AS DATE)
FROM Production.Product
WHERE ProductNumber < 'BL';



INSERT INTO PD_LKP (PD_NUM, EFF_DT, END_DATE)
SELECT DISTINCT ProductNumber, DATEADD(DAY, -34 , CAST(SYSDATETIME() AS DATE)), DATEADD(DAY, -17 , CAST(SYSDATETIME() AS DATE))
FROM Production.Product
WHERE ProductNumber BETWEEN 'BL' AND 'GT';

INSERT INTO PD_LKP (PD_NUM, EFF_DT, END_DATE)
SELECT DISTINCT ProductNumber, DATEADD(DAY, -16 , CAST(SYSDATETIME() AS DATE)), DATEADD(DAY, -7 , CAST(SYSDATETIME() AS DATE))
FROM Production.Product
WHERE ProductNumber BETWEEN 'BL' AND 'GT';

INSERT INTO PD_LKP (PD_NUM, EFF_DT)
SELECT DISTINCT ProductNumber, CAST(SYSDATETIME() AS DATE)
FROM Production.Product
WHERE ProductNumber BETWEEN 'BL' AND 'GT';


--============================================================

CREATE TABLE EXCH_RATE (
CCY_CODE VARCHAR(3),
RATE FLOAT,
EFF_DT DATE NOT NULL,
END_DATE DATE NOT NULL,
CRT_USR_NM VARCHAR(MAX) NOT NULL DEFAULT SUSER_NAME(),
CRT_DTM DATETIME2(7) NOT NULL DEFAULT SYSDATETIME()
);

INSERT INTO EXCH_RATE (CCY_CODE, RATE, EFF_DT, END_DATE)
VALUES ('EUR', 0.9, DATEADD(DAY, -10 , CAST(SYSDATETIME() AS DATE)), DATEADD(DAY, -6 , CAST(SYSDATETIME() AS DATE))),
('EUR', 0.87, DATEADD(DAY, -5 , CAST(SYSDATETIME() AS DATE)), DATEADD(DAY, -2 , CAST(SYSDATETIME() AS DATE))),
('EUR', 0.83, DATEADD(DAY, -1 , CAST(SYSDATETIME() AS DATE)), DATEADD(DAY, 5 , CAST(SYSDATETIME() AS DATE))),
('CAD', 0.8, DATEADD(DAY, -10 , CAST(SYSDATETIME() AS DATE)), DATEADD(DAY, -6 , CAST(SYSDATETIME() AS DATE))),
('CAD', 0.77, DATEADD(DAY, -5 , CAST(SYSDATETIME() AS DATE)), DATEADD(DAY, -2 , CAST(SYSDATETIME() AS DATE))),
('CAD', 0.73, DATEADD(DAY, -1 , CAST(SYSDATETIME() AS DATE)), DATEADD(DAY, 5 , CAST(SYSDATETIME() AS DATE))),
('GBP', 1.1, DATEADD(DAY, -10 , CAST(SYSDATETIME() AS DATE)), DATEADD(DAY, -6 , CAST(SYSDATETIME() AS DATE))),
('GBP', 1.17, DATEADD(DAY, -5 , CAST(SYSDATETIME() AS DATE)), DATEADD(DAY, -2 , CAST(SYSDATETIME() AS DATE))),
('GBP', 1.15, DATEADD(DAY, -1 , CAST(SYSDATETIME() AS DATE)), DATEADD(DAY, 5 , CAST(SYSDATETIME() AS DATE)))
;


--=============================================

CREATE SEQUENCE TxnSeq AS INT START WITH 1 INCREMENT BY 1;


CREATE TABLE SRC_TXN (
SEQ_NUM INT PRIMARY KEY DEFAULT NEXT VALUE FOR TxnSeq,
TXN_SRC_KEY AS SRC_CODE + CAST(SEQ_NUM AS VARCHAR(MAX)) + AC_NUM + REPLACE(REPLACE(REPLACE(REPLACE(convert(varchar, CRT_DTM, 121), '-', ''), ':', ''), '.', ''), ' ', ''),
SRC_CODE VARCHAR(6),
AC_NUM VARCHAR(MAX),
PD_NUM VARCHAR(MAX),
SHARES INT,
CCY VARCHAR(3),
BUS_DY DATE,
BKG_DT DATE,
CRT_USR_NM VARCHAR(MAX) NOT NULL DEFAULT SUSER_NAME(),
CRT_DTM DATETIME2(7) NOT NULL DEFAULT SYSDATETIME()
);


INSERT INTO SRC_TXN (SRC_CODE, AC_NUM, PD_NUM, SHARES, CCY, BUS_DY, BKG_DT)
VALUES ('STNDRT', '13909262', 'BK-M82S-48', 110, 'USD', '2022-11-18', '2022-11-19'),
('INTNTL', '1A68CD62', 'BB-9108', 176, 'EUR', '2022-11-15', NULL);


--=================
CREATE SEQUENCE TxnTgtSeq AS INT START WITH 1 INCREMENT BY 1;

CREATE TABLE TXN (
TXN_ID INT UNIQUE DEFAULT NEXT VALUE FOR TxnTgtSeq,
TXN_SRC_KEY VARCHAR(MAX),
AC_ID INT,
PD_ID INT,
SRC_STM_ID INT,
QTY INT,
CCY VARCHAR(3),
AMOUNT FLOAT,
TD DATE,
BKG_DT DATE,
CRT_USR_NM VARCHAR(MAX) NOT NULL DEFAULT SUSER_NAME(),
CRT_DTM DATETIME2(7) NOT NULL DEFAULT SYSDATETIME()
);



--=======================================

CREATE TABLE J$SRC_TXN
(
TXN_SRC_KEY VARCHAR(MAX),
CONSUME_F VARCHAR(1),
ACTION_F VARCHAR(1),
CRT_USR_NM VARCHAR(MAX) NOT NULL DEFAULT SUSER_NAME(),
CRT_DTM DATETIME2(7) NOT NULL DEFAULT SYSDATETIME()
);


--=======================================


CREATE TABLE EXCP_CODE (
EXCP_CODE_ID INT PRIMARY KEY,
EXCP_CODE_NM VARCHAR(MAX),
EXCP_CODE_DESC VARCHAR(MAX),
CRT_USR_NM VARCHAR(MAX) NOT NULL DEFAULT SUSER_NAME(),
CRT_DTM DATETIME2(7) NOT NULL DEFAULT SYSDATETIME()
);

INSERT INTO EXCP_CODE (EXCP_CODE_ID, EXCP_CODE_NM, EXCP_CODE_DESC)
VALUES
(1, 'ACEXCP', 'Account Number lookup failed'),
(2, 'PDEXCP', 'Product Number lookup failed'),
(3, 'GENEXCP', 'Something went wrong');


--========================================


CREATE TABLE TXN_EXCP (
TXN_SRC_KEY VARCHAR(MAX),
EXCP_CODE_ID INT,
CRT_USR_NM VARCHAR(MAX) NOT NULL DEFAULT SUSER_NAME(),
CRT_DTM DATETIME2(7) NOT NULL DEFAULT SYSDATETIME()
);

GO