USE AdventureWorks2019
GO

SELECT * FROM SRC_STM_LKP
SELECT * FROM AC_LKP
SELECT * FROM PD_LKP
SELECT * FROM EXCH_RATE
SELECT * FROM SRC_TXN
SELECT * FROM TXN
SELECT * FROM J$SRC_TXN
SELECT * FROM EXCP_CODE
SELECT * FROM TXN_EXCP

EXEC ETL_TransactionData 

GO